[client]
showSidebarNavigation = false

[theme]
base="dark"
primaryColor="#1DB954"  # Customize the primary color
backgroundColor="#121212"
secondaryBackgroundColor="#1A1A1A"
textColor="#FFFFFF"
font="sans serif"